services:
  - type: web
    name: PREDICT-FETO
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      # python preload.py  # opcional, solo si creas este archivo
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ProyectoFinal.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        fromDatabase: "django-insecure-ax!4glh(e@c6kjz&x4yx96q*6_c&jhi!+eg4l-u^km7bi5=#=z"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "127.0.0.1,localhost,predicci-n-fetal.onrender.com"
