services:
  - type: web
    name: PREDICT-FETO
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      # python preload.py  # opcional, solo si creas este archivo
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ProyectoFinal.wsgi:application --bind 0.0.0.0:$PORT --timeout 180 --workers 1
    envVars:
      - key: DJANGO_SECRET_KEY
        fromDatabase: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "127.0.0.1,localhost,predicci-n-fetal.onrender.com"
