# Generated by Django 5.2 on 2025-05-12 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('edad', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('edad_gestacional', models.IntegerField()),
                ('resultado_log', models.CharField(max_length=10)),
                ('resultado_svm', models.CharField(max_length=10)),
                ('resultado_rna', models.CharField(max_length=10)),
                ('resultado_mcd', models.CharField(max_length=10)),
            ],
        ),
    ]
