# Generated by Django 5.2 on 2025-05-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialprediccion',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='historialprediccion',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='historialprediccion',
            name='edad_gestacional',
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C1',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C10',
            field=models.IntegerField(default=0, verbose_name='Interval hypertension to delivery'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C11',
            field=models.IntegerField(default=0, verbose_name='Gestational age edema onset'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C12',
            field=models.IntegerField(default=0, verbose_name='Interval edema to delivery'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C13',
            field=models.IntegerField(default=0, verbose_name='Gestational age proteinuria onset'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C14',
            field=models.IntegerField(default=0, verbose_name='Interval proteinuria to delivery'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C15',
            field=models.IntegerField(default=0, verbose_name='Expectant treatment'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C16',
            field=models.IntegerField(default=0, verbose_name='Antihypertensive before hosp'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C17',
            field=models.IntegerField(default=0, verbose_name='Past history'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C18',
            field=models.FloatField(default=0.0, verbose_name='Max systolic BP'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C19',
            field=models.FloatField(default=0.0, verbose_name='Max diastolic BP'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C2',
            field=models.FloatField(default=0.0, verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C20',
            field=models.IntegerField(default=0, verbose_name='Reasons for delivery'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C21',
            field=models.IntegerField(default=0, verbose_name='Mode of delivery'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C22',
            field=models.FloatField(default=0.0, verbose_name='Max BNP'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C23',
            field=models.FloatField(default=0.0, verbose_name='Max creatinine'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C24',
            field=models.FloatField(default=0.0, verbose_name='Max uric acid'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C25',
            field=models.FloatField(default=0.0, verbose_name='Max proteinuria'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C26',
            field=models.FloatField(default=0.0, verbose_name='Max total protein'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C27',
            field=models.FloatField(default=0.0, verbose_name='Max albumin'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C28',
            field=models.FloatField(default=0.0, verbose_name='Max ALT'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C29',
            field=models.FloatField(default=0.0, verbose_name='Max AST'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C3',
            field=models.IntegerField(default=0, verbose_name='Gestational age of delivery'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C30',
            field=models.FloatField(default=0.0, verbose_name='Max platelet'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C4',
            field=models.IntegerField(default=0, verbose_name='Gravidity'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C5',
            field=models.IntegerField(default=0, verbose_name='Parity'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C6',
            field=models.IntegerField(default=0, verbose_name='Initial onset symptoms'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C7',
            field=models.IntegerField(default=0, verbose_name='Gestational age of IOS onset'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C8',
            field=models.IntegerField(default=0, verbose_name='Interval IOS to delivery'),
        ),
        migrations.AddField(
            model_name='historialprediccion',
            name='C9',
            field=models.IntegerField(default=0, verbose_name='Gestational age hypertension onset'),
        ),
        migrations.AlterField(
            model_name='historialprediccion',
            name='resultado_mcd',
            field=models.CharField(max_length=50),
        ),
    ]
