# Generated by Django 5.1.2 on 2025-05-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0002_remove_historialprediccion_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprediccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
